// components/faculty/AddFaculty.jsx
import React, { useState, useEffect } from "react";
import { useNavigate, Link } from "react-router-dom";
import { facultyAPI } from "../../services/api";
import { courseAPI } from "../../services/api";
import {
  Save,
  X,
  Calendar,
  User,
  Phone,
  Mail,
  Home,
  DollarSign,
  Copy,
  Check,
} from "lucide-react";
import "./AddFaculty.css";

const AddFaculty = () => {
  const navigate = useNavigate();

  const [formData, setFormData] = useState({
  dateOfJoining: "",
  facultyName: "",
  fathersName: "",
  shiftStart: "",
  shiftEnd: "",
  lunchStart: "",
  lunchEnd: "",
  dateOfBirth: "",
  email: "",
  basicStipend: "",
  mobileNo: "",
  whatsappNo: "",
  address: "",
  fatherContactNo: "",
  motherContactNo: "",
  courseAllotted: "",
});

  const [errors, setErrors] = useState({});
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [autoGeneratedNo] = useState(
    "FAC" + Math.floor(1000 + Math.random() * 9000)
  );

  // NEW STATES FOR PASSWORD MODAL
  const [createdFaculty, setCreatedFaculty] = useState(null);
  const [showPasswordModal, setShowPasswordModal] = useState(false);
  const [facultyPassword, setFacultyPassword] = useState("");
  const [isPasswordCopied, setIsPasswordCopied] = useState(false);

  const formatTo12Hour = (time24) => {
  if (!time24) return "";
  const [hours, minutes] = time24.split(":").map(Number);
  const period = hours >= 12 ? "PM" : "AM";
  const hours12 = hours % 12 || 12;
  return `${hours12}:${String(minutes).padStart(2, "0")} ${period}`;
};

  // Format name to Proper Case
  const formatName = (name) => {
    if (!name) return "";
    return name
      .toLowerCase()
      .split(" ")
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
      .join(" ");
  };

  // Format phone number to exactly 10 digits
  const formatPhoneNumber = (phone) => {
    if (!phone) return "";
    // Remove all non-digits and take first 10 characters
    const digits = phone.replace(/\D/g, "").slice(0, 10);
    return digits;
  };

  const handleInputChange = (e) => {
    const { name, value } = e.target;

    let formattedValue = value;

    // Apply formatting based on field type
    if (name === "facultyName" || name === "fathersName") {
      formattedValue = formatName(value);
    } else if (
      name === "mobileNo" ||
      name === "whatsappNo" ||
      name === "fatherContactNo" ||
      name === "motherContactNo"
    ) {
      formattedValue = formatPhoneNumber(value);
    } else if (name === "basicStipend") {
      formattedValue = value.replace(/[^0-9]/g, "");
    } else if (name === "email") {
      formattedValue = value;
    } else if (name === "address") {
      formattedValue = value.charAt(0).toUpperCase() + value.slice(1);
    }

    setFormData({
      ...formData,
      [name]: formattedValue,
    });

    // Clear error when user starts typing
    if (errors[name]) {
      setErrors({
        ...errors,
        [name]: "",
      });
    }
  };

  const [courses, setCourses] = useState([]);
  const [loadingCourses, setLoadingCourses] = useState(false);
  const [courseError, setCourseError] = useState(null);
  
  useEffect(() => {
    fetchCourses();
  }, []);

  const fetchCourses = async () => {
    try {
      setLoadingCourses(true);
      setCourseError(null);

      const response = await courseAPI.getActiveCourses();

      if (response.data.success) {
        setCourses(response.data.data || []);
      } else {
        throw new Error(response.data.message || "Failed to load courses");
      }
    } catch (err) {
      console.error("Error fetching courses:", err);
      setCourseError(
        err.message || "Failed to load courses. Using default options."
      );

      // Fallback courses in case API fails
      setCourses([
        {
          _id: "1",
          courseFullName: "B.Tech Computer Science",
          courseShortName: "BTech CS",
        },
        { _id: "2", courseFullName: "MBA", courseShortName: "MBA" },
        { _id: "3", courseFullName: "BBA", courseShortName: "BBA" },
        { _id: "4", courseFullName: "BCA", courseShortName: "BCA" },
        { _id: "5", courseFullName: "M.Tech", courseShortName: "MTech" },
      ]);
    } finally {
      setLoadingCourses(false);
    }
  };

  const validateForm = () => {
    const newErrors = {};
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    const phoneRegex = /^\d{10}$/;

    // Required field validation
    const requiredFields = [
  "dateOfJoining",
  "facultyName",
  "fathersName",
  "shiftStart",
  "shiftEnd",
  "lunchStart",
  "lunchEnd",
  "dateOfBirth",
  "email",
  "basicStipend",
  "mobileNo",
  "address",
  "fatherContactNo",
  "motherContactNo",
  "courseAllotted",
];

if (formData.shiftStart && formData.shiftEnd && formData.shiftStart >= formData.shiftEnd) {
  newErrors.shiftEnd = "End time must be after start time";
}
if (formData.lunchStart && formData.lunchEnd && formData.lunchStart >= formData.lunchEnd) {
  newErrors.lunchEnd = "Lunch end time must be after start time";
}

    requiredFields.forEach((field) => {
      if (!formData[field] || !formData[field].toString().trim()) {
        newErrors[field] = "This field is required";
      }
    });

    // Email validation
    if (formData.email && !emailRegex.test(formData.email)) {
      newErrors.email = "Please enter a valid email address";
    }

    // Phone number validation (must be exactly 10 digits)
    const phoneFields = [
      "mobileNo",
      "whatsappNo",
      "fatherContactNo",
      "motherContactNo",
    ];
    phoneFields.forEach((field) => {
      if (formData[field] && !phoneRegex.test(formData[field])) {
        newErrors[field] = "Phone number must be exactly 10 digits";
      }
    });

    // WhatsApp number is optional, but if provided, must be 10 digits
    if (formData.whatsappNo && !phoneRegex.test(formData.whatsappNo)) {
      newErrors.whatsappNo = "WhatsApp number must be exactly 10 digits";
    }

    // Basic stipend validation
    if (formData.basicStipend && parseInt(formData.basicStipend) <= 0) {
      newErrors.basicStipend = "Stipend must be greater than 0";
    }

    // Date validation: Date of joining should be after date of birth
    if (formData.dateOfJoining && formData.dateOfBirth) {
      const joinDate = new Date(formData.dateOfJoining);
      const birthDate = new Date(formData.dateOfBirth);
      if (joinDate < birthDate) {
        newErrors.dateOfJoining =
          "Date of joining cannot be before date of birth";
      }
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  // NEW: Function to copy password to clipboard
  const copyToClipboard = () => {
    navigator.clipboard.writeText(facultyPassword)
      .then(() => {
        setIsPasswordCopied(true);
        setTimeout(() => setIsPasswordCopied(false), 2000);
      })
      .catch(err => {
        console.error("Failed to copy: ", err);
      });
  };

  // NEW: Function to handle modal close
  const handleClosePasswordModal = () => {
    setShowPasswordModal(false);
    setCreatedFaculty(null);
    setFacultyPassword("");
    setIsPasswordCopied(false);
    
    // Navigate back to faculty list
    navigate(`${basePath}/faculty`);
  };

  // UPDATED handleSubmit function
  const handleSubmit = async (e) => {
    e.preventDefault();

    if (!validateForm()) {
      alert("Please fill all required fields before submitting.");
      return;
    }

    setIsSubmitting(true);

    try {
      // Prepare data for API
      const facultyData = {
        facultyNo: autoGeneratedNo,
        facultyName: formData.facultyName,
        fathersName: formData.fathersName,
        dateOfJoining: formData.dateOfJoining,
        dateOfBirth: formData.dateOfBirth,
        shift: `${formData.shiftStart}-${formData.shiftEnd}`,
       lunchTime: `${formData.lunchStart}-${formData.lunchEnd}`,
        email: formData.email,
        mobileNo: formData.mobileNo,
        whatsappNo: formData.whatsappNo || formData.mobileNo, // Default to mobile
        address: formData.address,
        fatherContactNo: formData.fatherContactNo,
        motherContactNo: formData.motherContactNo,
        basicStipend: parseFloat(formData.basicStipend) || 0,
        status: "active", // Default status
        courseAssigned: formData.courseAllotted,
      };

      // Call API
      const response = await facultyAPI.createFaculty(facultyData);

      if (response.data.success) {
        // Show success modal with password
        setCreatedFaculty(response.data.data.faculty || response.data.data);
        
        // Check if password is returned from backend
        if (response.data.data.user && response.data.data.user.defaultPassword) {
          setFacultyPassword(response.data.data.user.defaultPassword);
        } else {
          setFacultyPassword("Faculty@123"); // Default fallback
        }
        
        setShowPasswordModal(true);
        
        // Reset form
        setFormData({
  dateOfJoining: "",
  facultyName: "",
  fathersName: "",
  shiftStart: "",
  shiftEnd: "",
  lunchStart: "",
  lunchEnd: "",
  dateOfBirth: "",
  email: "",
  basicStipend: "",
  mobileNo: "",
  whatsappNo: "",
  address: "",
  fatherContactNo: "",
  motherContactNo: "",
  courseAllotted: "",
});
        setErrors({});
        
      } else {
        throw new Error(response.data.message || "Failed to add faculty");
      }
    } catch (err) {
      console.error("Error adding faculty:", err);
      alert(
        err.response?.data?.message ||
          "Failed to add faculty. Please try again."
      );
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleCancel = () => {
    if (
      window.confirm(
        "Are you sure you want to cancel? All unsaved changes will be lost."
      )
    ) {
      navigate(`${basePath}/faculty`);
    }
  };

  const handleKeyDown = (e) => {
    if (e.key === "Enter") {
      e.preventDefault();
      const form = e.target.form;
      const focusableElements = form.querySelectorAll(
        'input:not([type="radio"]):not([type="checkbox"]), select, textarea, button'
      );
      const currentIndex = Array.from(focusableElements).indexOf(e.target);
      if (currentIndex < focusableElements.length - 1) {
        const nextElement = focusableElements[currentIndex + 1];
        if (
          nextElement.tagName !== "BUTTON" ||
          currentIndex === focusableElements.length - 2
        ) {
          nextElement.focus();
        }
      }
    }
  };

  const handleReset = () => {
    setFormData({
      dateOfJoining: "",
      facultyName: "",
      fathersName: "",
      shift: "",
      lunchTime: "",
      dateOfBirth: "",
      email: "",
      basicStipend: "",
      mobileNo: "",
      whatsappNo: "",
      address: "",
      fatherContactNo: "",
      motherContactNo: "",
      dateOfLeaving: "",
      courseAllotted: "",
    });
    setErrors({});
  };

  return (
    <div className="new-enquiry-container">
      {/* Header */}
      <div className="page-header">
        <div className="header-left">
          <Link to={`${basePath}/faculty`} className="back-link">
            <X size={20} />
            Cancel
          </Link>
          <div>
            <h1>Add New Faculty</h1>
            <p>Fill in the details for new faculty member</p>
          </div>
        </div>
        <div className="header-actions">
          <button
            onClick={handleSubmit}
            disabled={isSubmitting}
            className="btn-primary"
            type="submit"
          >
            <Save size={18} />
            {isSubmitting ? "Submitting..." : "Add Faculty"}
          </button>
        </div>
      </div>

      <form onSubmit={handleSubmit} className="enquiry-form">
        {/* Section 1: Faculty Details */}
        <div className="form-card">
          <div className="card-header">
            <User size={20} />
            <h3>Faculty Details</h3>
          </div>
          <div className="card-content">
            <div className="form-grid">
              <div className="form-group">
                <label>Faculty No</label>
                <input
                  type="text"
                  value={autoGeneratedNo}
                  readOnly
                  className="enquiry-no"
                />
              </div>

              <div className="form-group">
                <label>
                  Date of Joining <span className="required-star">*</span>
                </label>
                <input
                  type="date"
                  name="dateOfJoining"
                  value={formData.dateOfJoining}
                  onChange={handleInputChange}
                  onKeyDown={handleKeyDown}
                  max={new Date().toISOString().split("T")[0]}
                  className={errors.dateOfJoining ? "error-field" : ""}
                />
                {errors.dateOfJoining && (
                  <span className="error-text">{errors.dateOfJoining}</span>
                )}
              </div>

              <div className="form-group">
                <label>
                  Faculty Name <span className="required-star">*</span>
                </label>
                <input
                  type="text"
                  name="facultyName"
                  value={formData.facultyName}
                  onChange={handleInputChange}
                  onKeyDown={handleKeyDown}
                  placeholder="Full name of faculty"
                  className={errors.facultyName ? "error-field" : ""}
                />
                {errors.facultyName && (
                  <span className="error-text">{errors.facultyName}</span>
                )}
              </div>

              <div className="form-group">
                <label>
                  Father's Name <span className="required-star">*</span>
                </label>
                <input
                  type="text"
                  name="fathersName"
                  value={formData.fathersName}
                  onChange={handleInputChange}
                  onKeyDown={handleKeyDown}
                  placeholder="Father's name"
                  className={errors.fathersName ? "error-field" : ""}
                />
                {errors.fathersName && (
                  <span className="error-text">{errors.fathersName}</span>
                )}
              </div>

              <div className="form-group">
                <label>
                  Date of Birth <span className="required-star">*</span>
                </label>
                <input
                  type="date"
                  name="dateOfBirth"
                  value={formData.dateOfBirth}
                  onChange={handleInputChange}
                  onKeyDown={handleKeyDown}
                  max={new Date().toISOString().split("T")[0]}
                  className={errors.dateOfBirth ? "error-field" : ""}
                />
                {errors.dateOfBirth && (
                  <span className="error-text">{errors.dateOfBirth}</span>
                )}
              </div>

              <div className="form-group">
                <label>
                  Course Allotted <span className="required-star">*</span>
                </label>
                <select
                  name="courseAllotted"
                  value={formData.courseAllotted}
                  onChange={handleInputChange}
                  onKeyDown={handleKeyDown}
                  className={errors.courseAllotted ? "error-field" : ""}
                  disabled={loadingCourses}
                >
                  <option value="">
                    {loadingCourses ? "Loading courses..." : "Select Course"}
                  </option>
                  {courses.map((course) => (
                    <option key={course._id} value={course.courseFullName}>
                      {" "}
                      {/* Send name */}
                      {course.courseFullName}
                      {course.courseShortName
                        ? ` (${course.courseShortName})`
                        : ""}
                    </option>
                  ))}
                  <option value="">Not Allotted</option>
                  <option value="general_subjects">General Subjects</option>
                  <option value="not_allotted">Not Allotted</option>
                </select>

                {/* Show loading or error messages */}
                {loadingCourses && (
                  <span className="loading-text">Loading courses...</span>
                )}
                {courseError && !loadingCourses && (
                  <span
                    className="error-text"
                    style={{ color: "orange", fontSize: "12px" }}
                  >
                    ⚠️ {courseError}
                  </span>
                )}
                {errors.courseAllotted && (
                  <span className="error-text">{errors.courseAllotted}</span>
                )}
              </div>
            </div>
          </div>
        </div>

        {/* Section 2: Work Details */}
        {/* Section 2: Work Details */}
<div className="form-card">
  <div className="card-header">
    <Calendar size={20} />
    <h3>Work Details</h3>
  </div>
  <div className="card-content">
    <div className="form-grid">

      {/* Shift time range */}
      <div className="form-group full-width">
        <label>
          Faculty Timing Shift <span className="required-star">*</span>
        </label>
        <div className="time-range-wrapper">
          <div className="time-range-inputs">
            <input
              type="time"
              name="shiftStart"
              value={formData.shiftStart}
              onChange={handleInputChange}
              onKeyDown={handleKeyDown}
              className={errors.shiftStart ? "error-field" : ""}
            />
            <span className="time-range-separator">to</span>
            <input
              type="time"
              name="shiftEnd"
              value={formData.shiftEnd}
              onChange={handleInputChange}
              onKeyDown={handleKeyDown}
              className={errors.shiftEnd ? "error-field" : ""}
            />
          </div>
          {formData.shiftStart && formData.shiftEnd && (
            <span className="time-range-display">
              {formatTo12Hour(formData.shiftStart)} to {formatTo12Hour(formData.shiftEnd)}
            </span>
          )}
        </div>
        {errors.shiftStart && <span className="error-text">{errors.shiftStart}</span>}
        {errors.shiftEnd && <span className="error-text">{errors.shiftEnd}</span>}
      </div>

      {/* Lunch time range */}
      <div className="form-group full-width">
        <label>
          Faculty Lunch Time <span className="required-star">*</span>
        </label>
        <div className="time-range-wrapper">
          <div className="time-range-inputs">
            <input
              type="time"
              name="lunchStart"
              value={formData.lunchStart}
              onChange={handleInputChange}
              onKeyDown={handleKeyDown}
              className={errors.lunchStart ? "error-field" : ""}
            />
            <span className="time-range-separator">to</span>
            <input
              type="time"
              name="lunchEnd"
              value={formData.lunchEnd}
              onChange={handleInputChange}
              onKeyDown={handleKeyDown}
              className={errors.lunchEnd ? "error-field" : ""}
            />
          </div>
          {formData.lunchStart && formData.lunchEnd && (
            <span className="time-range-display">
              {formatTo12Hour(formData.lunchStart)} to {formatTo12Hour(formData.lunchEnd)}
            </span>
          )}
        </div>
        {errors.lunchStart && <span className="error-text">{errors.lunchStart}</span>}
        {errors.lunchEnd && <span className="error-text">{errors.lunchEnd}</span>}
      </div>

      <div className="form-group">
        <label>
          Basic Stipend (₹) <span className="required-star">*</span>
        </label>
        <input
          type="text"
          name="basicStipend"
          value={formData.basicStipend}
          onChange={handleInputChange}
          onKeyDown={handleKeyDown}
          placeholder="Monthly stipend amount"
          className={errors.basicStipend ? "error-field" : ""}
        />
        {errors.basicStipend && (
          <span className="error-text">{errors.basicStipend}</span>
        )}
      </div>

    </div>
  </div>
</div>

        {/* Section 3: Contact Information */}
        <div className="form-sections-row">
          {/* Left Column - Contact Details */}
          <div className="form-column">
            <div className="form-card">
              <div className="card-header">
                <Phone size={20} />
                <h3>Contact Information</h3>
              </div>
              <div className="card-content">
                <div className="form-grid">
                  <div className="form-group">
                    <label>
                      Mobile No <span className="required-star">*</span>
                    </label>
                    <input
                      type="tel"
                      name="mobileNo"
                      value={formData.mobileNo}
                      onChange={handleInputChange}
                      onKeyDown={handleKeyDown}
                      placeholder="10 digit mobile number"
                      maxLength="10"
                      className={errors.mobileNo ? "error-field" : ""}
                    />
                    {errors.mobileNo && (
                      <span className="error-text">{errors.mobileNo}</span>
                    )}
                  </div>

                  <div className="form-group">
                    <label>WhatsApp No</label>
                    <input
                      type="tel"
                      name="whatsappNo"
                      value={formData.whatsappNo}
                      onChange={handleInputChange}
                      onKeyDown={handleKeyDown}
                      placeholder="10 digit WhatsApp number"
                      maxLength="10"
                      className={errors.whatsappNo ? "error-field" : ""}
                    />
                    {errors.whatsappNo && (
                      <span className="error-text">{errors.whatsappNo}</span>
                    )}
                  </div>

                  <div className="form-group">
                    <label>
                      Email ID <span className="required-star">*</span>
                    </label>
                    <input
                      type="email"
                      name="email"
                      value={formData.email}
                      onChange={handleInputChange}
                      onKeyDown={handleKeyDown}
                      placeholder="email@example.com"
                      className={errors.email ? "error-field" : ""}
                    />
                    {errors.email && (
                      <span className="error-text">{errors.email}</span>
                    )}
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Right Column - Parent Contact Details */}
          <div className="form-column">
            <div className="form-card">
              <div className="card-header">
                <User size={20} />
                <h3>Parent Contact Details</h3>
              </div>
              <div className="card-content">
                <div className="form-grid">
                  <div className="form-group">
                    <label>
                      Father Contact No <span className="required-star">*</span>
                    </label>
                    <input
                      type="tel"
                      name="fatherContactNo"
                      value={formData.fatherContactNo}
                      onChange={handleInputChange}
                      onKeyDown={handleKeyDown}
                      placeholder="10 digit contact number"
                      maxLength="10"
                      className={errors.fatherContactNo ? "error-field" : ""}
                    />
                    {errors.fatherContactNo && (
                      <span className="error-text">
                        {errors.fatherContactNo}
                      </span>
                    )}
                  </div>

                  <div className="form-group">
                    <label>
                      Mother Contact No <span className="required-star">*</span>
                    </label>
                    <input
                      type="tel"
                      name="motherContactNo"
                      value={formData.motherContactNo}
                      onChange={handleInputChange}
                      onKeyDown={handleKeyDown}
                      placeholder="10 digit contact number"
                      maxLength="10"
                      className={errors.motherContactNo ? "error-field" : ""}
                    />
                    {errors.motherContactNo && (
                      <span className="error-text">
                        {errors.motherContactNo}
                      </span>
                    )}
                  </div>

                  <div className="form-group full-width">
                    <label>
                      Address <span className="required-star">*</span>
                    </label>
                    <input
                      type="text"
                      name="address"
                      value={formData.address}
                      onChange={handleInputChange}
                      onKeyDown={handleKeyDown}
                      placeholder="Complete address"
                      className={errors.address ? "error-field" : ""}
                    />
                    {errors.address && (
                      <span className="error-text">{errors.address}</span>
                    )}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Form Actions */}
        <div className="form-actions">
          <button type="button" onClick={handleReset} className="btn-reset">
            Reset Form
          </button>
          <button type="submit" disabled={isSubmitting} className="btn-submit">
            {isSubmitting ? "Submitting..." : "Add Faculty"}
          </button>
        </div>
      </form>

      {/* NEW: Password Success Modal */}
      {showPasswordModal && createdFaculty && (
        <div className="modal-overlay">
          <div className="modal-content">
            <div className="modal-header">
              <h2>✅ Faculty Created Successfully!</h2>
              <button onClick={handleClosePasswordModal} className="close-button">
                ×
              </button>
            </div>
            
            <div className="modal-body">
              <div className="success-icon">
                <svg width="60" height="60" viewBox="0 0 24 24" fill="none" stroke="#10b981" strokeWidth="2">
                  <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"></path>
                  <polyline points="22 4 12 14.01 9 11.01"></polyline>
                </svg>
              </div>
              
              <div className="faculty-info">
                <h3>{createdFaculty.facultyName}</h3>
                <p><strong>Faculty No:</strong> {createdFaculty.facultyNo}</p>
                <p><strong>Email:</strong> {createdFaculty.email}</p>
                <p><strong>Course:</strong> {createdFaculty.courseAssigned || "Not Assigned"}</p>
              </div>
              
              <div className="password-section">
                <h4>Login Credentials</h4>
                <div className="password-display">
                  <div className="password-field">
                    <span className="password-label">Password:</span>
                    <span className="password-value">{facultyPassword}</span>
                    <button onClick={copyToClipboard} className="copy-button">
                      {isPasswordCopied ? <Check size={16} /> : <Copy size={16} />}
                      {isPasswordCopied ? "Copied!" : "Copy"}
                    </button>
                  </div>
                  <p className="password-note">
                    ⚠️ Please share this password with the faculty member securely. 
                    They should change it on first login.
                  </p>
                </div>
              </div>
              
              <div className="login-instructions">
                <h4>How to Login:</h4>
                <ol>
                  <li>Go to your institute login page</li>
                  <li>Username: <strong>{createdFaculty.email}</strong></li>
                  <li>Password: <strong>{facultyPassword}</strong></li>
                </ol>
              </div>
            </div>
            
            <div className="modal-footer">
              <button onClick={handleClosePasswordModal} className="btn-primary">
                Done
              </button>
              <button onClick={copyToClipboard} className="btn-secondary">
                {isPasswordCopied ? <Check size={16} /> : <Copy size={16} />}
                {isPasswordCopied ? "Copied!" : "Copy Password"}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default AddFaculty;